"""Immutable, self-validating values used by the media aggregate.

Constructing one of these types *is* the validation step: if you hold a
:class:`SourceUrl`, it is syntactically usable; if you hold a :class:`Checksum`,
its digest has the right shape for its algorithm. Entities can therefore be
written as pure state machines, free of defensive input checks.

Normalisation (trimming, lowercasing a scheme, collapsing separators) happens
inside ``__post_init__`` through ``object.__setattr__`` - the standard way to
finish initialising a frozen dataclass.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import ClassVar, Final
from urllib.parse import urlsplit, urlunsplit
from uuid import UUID

from mediahub.domain.common.value_object import ValueObject
from mediahub.domain.media.errors import (
    InvalidFileSizeError,
    InvalidMediaIdError,
    InvalidMediaTitleError,
    InvalidSourceUrlError,
    InvalidStorageKeyError,
)

_SUPPORTED_URL_SCHEMES: Final[frozenset[str]] = frozenset({"http", "https"})
_BYTES_PER_UNIT: Final[int] = 1024
_SIZE_UNITS: Final[tuple[str, ...]] = ("B", "KiB", "MiB", "GiB", "TiB", "PiB")


@dataclass(frozen=True, slots=True)
class MediaId(ValueObject):
    """Stable identifier of a media item.

    UUIDs are generated by the application layer through the
    :class:`~mediahub.application.common.ports.UuidGenerator` port, never by
    the domain, so aggregates stay deterministic under test.
    """

    value: UUID

    @classmethod
    def parse(cls, raw: str) -> MediaId:
        """Build an identifier from its canonical string form.

        Args:
            raw: A UUID in any form :class:`uuid.UUID` accepts.

        Returns:
            The parsed identifier.

        Raises:
            InvalidMediaIdError: If ``raw`` is not a valid UUID.
        """
        try:
            return cls(UUID(raw))
        except (ValueError, AttributeError, TypeError) as exc:
            raise InvalidMediaIdError(str(raw)) from exc

    def __str__(self) -> str:
        """Return the canonical string form of the identifier."""
        return str(self.value)


@dataclass(frozen=True, slots=True)
class MediaTitle(ValueObject):
    """Human-readable name of a media item.

    Surrounding whitespace is trimmed and inner runs of whitespace are
    collapsed, so two titles that only differ in spacing compare equal.
    """

    value: str

    MAX_LENGTH: ClassVar[int] = 500

    def __post_init__(self) -> None:
        """Normalise and validate the title."""
        normalised = " ".join(self.value.split()) if self.value else ""
        if not normalised:
            message = "A media title must not be empty."
            raise InvalidMediaTitleError(message)
        if len(normalised) > self.MAX_LENGTH:
            message = (
                f"A media title must be at most {self.MAX_LENGTH} characters, "
                f"got {len(normalised)}."
            )
            raise InvalidMediaTitleError(message)
        object.__setattr__(self, "value", normalised)

    def __str__(self) -> str:
        """Return the normalised title."""
        return self.value


@dataclass(frozen=True, slots=True)
class SourceUrl(ValueObject):
    """The remote location a media item originates from.

    Only ``http`` and ``https`` are accepted. The scheme and host are
    lowercased and the fragment is dropped, giving a canonical form suitable
    for duplicate detection.
    """

    value: str

    MAX_LENGTH: ClassVar[int] = 2048

    def __post_init__(self) -> None:
        """Normalise the URL and reject anything unusable."""
        raw = (self.value or "").strip()
        if not raw:
            raise InvalidSourceUrlError(raw, "the value is empty")
        if len(raw) > self.MAX_LENGTH:
            raise InvalidSourceUrlError(raw, f"longer than {self.MAX_LENGTH} characters")

        parts = urlsplit(raw)
        if parts.scheme.lower() not in _SUPPORTED_URL_SCHEMES:
            supported = ", ".join(sorted(_SUPPORTED_URL_SCHEMES))
            raise InvalidSourceUrlError(raw, f"scheme must be one of {supported}")
        if not parts.netloc:
            raise InvalidSourceUrlError(raw, "the host is missing")

        canonical = urlunsplit(
            (parts.scheme.lower(), parts.netloc.lower(), parts.path, parts.query, "")
        )
        object.__setattr__(self, "value", canonical)

    @property
    def host(self) -> str:
        """Return the hostname, without credentials or port."""
        return urlsplit(self.value).hostname or ""

    def __str__(self) -> str:
        """Return the canonical URL."""
        return self.value


@dataclass(frozen=True, slots=True)
class StorageKey(ValueObject):
    """Location of an item's bytes, relative to the configured library root.

    Keys are always relative POSIX paths. Absolute paths, Windows separators
    and ``..`` segments are rejected, which keeps every artefact inside the
    library root regardless of the storage adapter in use.
    """

    value: str

    MAX_LENGTH: ClassVar[int] = 1024

    def __post_init__(self) -> None:
        """Normalise the key and reject anything that could escape the root."""
        raw = (self.value or "").strip()
        if not raw:
            raise InvalidStorageKeyError(raw, "the value is empty")
        if len(raw) > self.MAX_LENGTH:
            raise InvalidStorageKeyError(raw, f"longer than {self.MAX_LENGTH} characters")
        if "\\" in raw:
            raise InvalidStorageKeyError(raw, "backslashes are not allowed, use '/'")
        if raw.startswith("/"):
            raise InvalidStorageKeyError(raw, "the key must be relative")

        segments = [segment for segment in raw.split("/") if segment not in {"", "."}]
        if not segments:
            raise InvalidStorageKeyError(raw, "the key resolves to an empty path")
        if any(segment == ".." for segment in segments):
            raise InvalidStorageKeyError(raw, "path traversal ('..') is not allowed")

        object.__setattr__(self, "value", "/".join(segments))

    @property
    def filename(self) -> str:
        """Return the last path segment."""
        return self.value.rsplit("/", maxsplit=1)[-1]

    def __str__(self) -> str:
        """Return the normalised, relative key."""
        return self.value


@dataclass(frozen=True, slots=True)
class FileSize(ValueObject):
    """A non-negative size in bytes.

    Bytes are the only unit stored; human-readable rendering is a presentation
    concern exposed through :attr:`human_readable` for logs and diagnostics.
    """

    bytes_: int

    def __post_init__(self) -> None:
        """Reject negative sizes."""
        if self.bytes_ < 0:
            message = f"A file size must be >= 0 bytes, got {self.bytes_}."
            raise InvalidFileSizeError(message)

    @classmethod
    def zero(cls) -> FileSize:
        """Return a size of zero bytes."""
        return cls(0)

    @property
    def human_readable(self) -> str:
        """Return the size using binary units, e.g. ``1.4 GiB``."""
        size = float(self.bytes_)
        for unit in _SIZE_UNITS:
            if size < _BYTES_PER_UNIT or unit == _SIZE_UNITS[-1]:
                return f"{size:.0f} {unit}" if unit == "B" else f"{size:.1f} {unit}"
            size /= _BYTES_PER_UNIT
        return f"{size:.1f} {_SIZE_UNITS[-1]}"  # pragma: no cover - unreachable guard

    def __str__(self) -> str:
        """Return the human-readable form."""
        return self.human_readable


# Content hashes live in the shared kernel as
# :class:`~mediahub.domain.common.fingerprint.Fingerprint`. The Catalogue uses
# one for duplicate detection and Delivery records one on a receipt; a
# Catalogue-local copy would let the two disagree about what "sha256" means.
